# Inventory Service specific configuration
server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_inventorydb?createDatabaseIfNotExist=true
    username: root
    password: drowssap
    driver-class-name: com.mysql.cj.jdbc.Driver

# Inventory service specific logging
logging:
  level:
    com.ecommerce.inventoryservice: DEBUG 