# Order Service specific configuration
server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_orderdb?createDatabaseIfNotExist=true
    username: root
    password: drowssap
    driver-class-name: com.mysql.cj.jdbc.Driver

# Order service specific logging
logging:
  level:
    com.ecommerce.orderservice: DEBUG 