# Product Service specific configuration
server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_productdb?createDatabaseIfNotExist=true
    username: root
    password: drowssap
    driver-class-name: com.mysql.cj.jdbc.Driver

# Product service specific logging
logging:
  level:
    com.ecommerce.productservice: DEBUG 