server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes: []
    discovery:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 